version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=smashing-thrush-62570.upstash.io
      - REDIS_PORT=6379
      - REDIS_PASSWORD=AfRqAAIjcDExN2M3YWUxMDlhYzI0YmVmYTc1M2ZhZTA2ODA4ODQ4OHAxMA
      - REDIS_URL=rediss://:AfRqAAIjcDExN2M3YWUxMDlhYzI0YmVmYTc1M2ZhZTA2ODA4ODQ4OHAxMA@smashing-thrush-62570.upstash.io:6379
      - DATABASE_URL=postgresql://gdg_owner:npg_6KgAVNc7Wvbt@ep-holy-glade-a15bd11p-pooler.ap-southeast-1.aws.neon.tech/gdg?sslmode=require
      - GEMINI_API_KEY=AIzaSyB28WeENOw0MM9vrWYNASxGOZAQ0nWyFlE
      - YOUTUBE_API_KEY=AIzaSyDJiTaRCMPVcMbA0lDvX0rFmKDJqICcJ9A
      - NODE_ENV=production
    restart: unless-stopped